### ISSUE TITLE
how to add scroll view when showing the list

### ISSUE THREAD

**Issue by sant527** [xcash/bootstrap-autocomplete#8]
I am able to show the list of matched items in the drop down box. But when the matched elements are long how to show them like a scroll view.

**Comment by bmatusiak** [comment]
i was able to achieve this with css, although it doesn't scroll with the arrow keys, but scroll does work with mouse wheel  and the bar shows, im sure some js can be accomplished to scroll on active selection
```css
.bootstrap-autocomplete.dropdown-menu{
    max-height: 200px;
    overflow-y: scroll;
}
```
